package it.cwmp.client.view.authentication

import akka.actor.{Actor, ActorRef}
import it.cwmp.client.controller.ActorAlertManagement
import it.cwmp.client.controller.messages.AuthenticationRequests.{LogIn, SignUp}
import it.cwmp.client.controller.messages.ViewCommon.{Hide, Initialize, Show}
import javafx.application.Platform
import javafx.embed.swing.JFXPanel

/**
  * Actor assigned to the management of the display of the authentication screen and of the events generated by it.
  *
  * @author Elia Di Pasquale
  */
case class AuthenticationViewActor() extends Actor with ActorAlertManagement {

  /**
    * Controller that deals with the graphic management of authentication components.
    */
  var fxAlertsController: AuthenticationFXController = _
  /**
    * Control actor through which messages for event management are received and sent.
    */
  var controllerActor: ActorRef = _

  /**
    * Method invoked at the start of the actor (N.B. Do not call directly).
    * Initializes and manages the controller to manage the graphic layout of the authentication section.
    */
  override def preStart(): Unit = {
    super.preStart()

    new JFXPanel // initializes JavaFX
    Platform setImplicitExit false
    Platform runLater (() => {
      fxAlertsController = AuthenticationFXController(new AuthenticationStrategy {
        override def performLogIn(username: String, password: String): Unit =
          controllerActor ! LogIn(username, password)

        override def performPasswordCheck(password: String, confirmPassword: String): Boolean =
          password == confirmPassword

        override def performSignUp(username: String, password: String): Unit =
          controllerActor ! SignUp(username, password)
      })
    })
  }

  override def receive: Receive = alertBehaviour orElse {
    case Initialize => controllerActor = sender()
    case Show => Platform runLater (() => fxAlertsController showGUI())
    case Hide => Platform runLater (() => {
      fxAlertsController hideGUI()
      fxAlertsController hideLoading()
    })
  }

  override protected def onErrorAlertReceived(title: String, message: String): Unit = {
    super.onErrorAlertReceived(title, message)
    onAlertReceived()
  }

  override protected def onInfoAlertReceived(title: String, message: String): Unit = {
    super.onInfoAlertReceived(title, message)
    onAlertReceived()
  }

  /**
    * When receiving an alert should enable buttons and hide loading
    */
  private def onAlertReceived(): Unit = {
    fxAlertsController enableViewComponents()
    fxAlertsController hideLoading()
  }

}
